// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  cta: dynamic(() => import("./Cta")),
  image: dynamic(() => import("./Image")),
  info: dynamic(() => import("./Info")),
};
